version: '3.8'
services:
  backend:
    image: meuuser/disparo-backend:latest
    volumes:
      - job_data:/app/backend/data
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: meuuser/disparo-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  job_data:
