version: "3.7"
services:
  backend:
    image: guihorst/dispatch-backend:latest
    env_file:
      - backend/.env
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
  frontend:
    image: guihorst/dispatch-frontend:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
