FROM node:18-alpine
WORKDIR /app

# Copy root package.json and install dependencies
COPY package.json ./
RUN npm install --production

# Copy backend application code
COPY backend ./backend

# Set working directory to backend
WORKDIR /app/backend
EXPOSE 3000

CMD ["node", "index.js"]
