version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "3000:3000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
